export let PinyinList = {
  yi: ['yī', 'yí', 'yǐ', 'yì'],
  er: ['ér', 'ěr', 'èr'],
  shi: ['shī', 'shí', 'shǐ', 'shì', 'shi'],
  ding: ['dīng', 'dǐng', 'dìng'],
  chang: ['chāng', 'cháng', 'chǎng', 'chàng'],
  qi: ['qī', 'qí', 'qǐ', 'qì'],
  bo: ['bō', 'bó', 'bǒ', 'bò', 'bo'],
  bu: ['bū', 'bú', 'bǔ', 'bù'],
  ba: ['bā', 'bá', 'bǎ', 'bà', 'ba'],
  ren: ['rén', 'rěn', 'rèn'],
  ru: ['rú', 'rǔ', 'rù'],
  bi: ['bī', 'bí', 'bǐ', 'bì'],
  ji: ['jī', 'jí', 'jǐ', 'jì'],
  jiu: ['jiū', 'jiǔ', 'jiù'],
  diao: ['diāo', 'diào'],
  le: ['lè', 'le'],
  liao: ['liāo', 'liáo', 'liǎo', 'liào'],
  dao: ['dāo', 'dáo', 'dǎo', 'dào'],
  li: ['lī', 'lí', 'lǐ', 'lì', 'li'],
  nai: ['nǎi', 'nài'],
  you: ['yōu', 'yóu', 'yǒu', 'yòu'],
  san: ['sān', 'sǎn', 'sàn'],
  gan: ['gān', 'gǎn', 'gàn'],
  yu: ['yū', 'yú', 'yǔ', 'yù'],
  kui: ['kuī', 'kuí', 'kuǐ', 'kuì'],
  gong: ['gōng', 'gǒng', 'gòng'],
  tu: ['tū', 'tú', 'tǔ', 'tù'],
  cai: ['cāi', 'cái', 'cǎi', 'cài'],
  xia: ['xiā', 'xiá', 'xià'],
  cun: ['cūn', 'cún', 'cǔn', 'cùn'],
  da: ['dā', 'dá', 'dǎ', 'dà', 'da'],
  dai: ['dāi', 'dǎi', 'dài'],
  zhang: ['zhāng', 'zhǎng', 'zhàng'],
  mo: ['mō', 'mó', 'mǒ', 'mò'],
  wan: ['wān', 'wán', 'wǎn', 'wàn'],
  shang: ['shāng', 'shǎng', 'shàng', 'shang'],
  xiao: ['xiāo', 'xiáo', 'xiǎo', 'xiào'],
  kou: ['kōu', 'kǒu', 'kòu'],
  shan: ['shān', 'shǎn', 'shàn'],
  jin: ['jīn', 'jǐn', 'jìn'],
  qian: ['qiān', 'qián', 'qiǎn', 'qiàn'],
  chuan: ['chuān', 'chuán', 'chuǎn', 'chuàn'],
  ge: ['gē', 'gé', 'gě', 'gè'],
  xi: ['xī', 'xí', 'xǐ', 'xì'],
  me: ['me'],
  shao: ['shāo', 'sháo', 'shǎo', 'shào'],
  fan: ['fān', 'fán', 'fǎn', 'fàn'],
  guang: ['guāng', 'guǎng', 'guàng'],
  wang: ['wāng', 'wáng', 'wǎng', 'wàng'],
  men: ['mēn', 'mén', 'mèn', 'men'],
  ya: ['yā', 'yá', 'yǎ', 'yà', 'ya'],
  zhi: ['zhī', 'zhí', 'zhǐ', 'zhì'],
  si: ['sī', 'sǐ', 'sì'],
  zi: ['zī', 'zǐ', 'zì'],
  wei: ['wēi', 'wéi', 'wěi', 'wèi'],
  ye: ['yē', 'yé', 'yě', 'yè'],
  nv: ['nǚ', 'nǜ'],
  fei: ['fēi', 'féi', 'fěi', 'fèi'],
  cha: ['chā', 'chá', 'chǎ', 'chà'],
  ma: ['mā', 'má', 'mǎ', 'mà', 'ma'],
  xiang: ['xiāng', 'xiáng', 'xiǎng', 'xiàng'],
  feng: ['fēng', 'féng', 'fěng', 'fèng'],
  kai: ['kāi', 'kǎi', 'kài'],
  jing: ['jīng', 'jǐng', 'jìng'],
  tian: ['tiān', 'tián', 'tiǎn', 'tiàn'],
  fu: ['fū', 'fú', 'fǔ', 'fù'],
  yuan: ['yuān', 'yuán', 'yuǎn', 'yuàn'],
  wu: ['wū', 'wú', 'wǔ', 'wù'],
  yun: ['yūn', 'yún', 'yǔn', 'yùn'],
  zhuan: ['zhuān', 'zhuǎn', 'zhuàn'],
  gai: ['gāi', 'gǎi', 'gài'],
  za: ['zā', 'zá', 'zǎ'],
  zha: ['zhā', 'zhá', 'zhǎ', 'zhà', 'zha'],
  mu: ['mú', 'mǔ', 'mù'],
  ting: ['tīng', 'tíng', 'tǐng', 'tìng'],
  quan: ['quān', 'quán', 'quǎn', 'quàn'],
  tai: ['tāi', 'tái', 'tài'],
  ou: ['ōu', 'ǒu', 'òu'],
  qu: ['qū', 'qú', 'qǔ', 'qù', 'qu'],
  pi: ['pī', 'pí', 'pǐ', 'pì'],
  che: ['chē', 'chě', 'chè'],
  ju: ['jū', 'jú', 'jǔ', 'jù'],
  tun: ['tūn', 'tún', 'tùn'],
  hu: ['hū', 'hú', 'hǔ', 'hù'],
  qie: ['qiē', 'qié', 'qiě', 'qiè'],
  wa: ['wā', 'wá', 'wǎ', 'wà', 'wa'],
  yue: ['yuē', 'yuě', 'yuè'],
  ri: ['rì'],
  zhong: ['zhōng', 'zhǒng', 'zhòng'],
  bei: ['bēi', 'běi', 'bèi', 'bei'],
  gang: ['gāng', 'gǎng', 'gàng'],
  nei: ['něi', 'nèi'],
  shui: ['shuí', 'shuǐ', 'shuì'],
  jian: ['jiān', 'jiǎn', 'jiàn'],
  xian: ['xiān', 'xián', 'xiǎn', 'xiàn'],
  niu: ['niū', 'niú', 'niǔ', 'niù'],
  shou: ['shōu', 'shóu', 'shǒu', 'shòu'],
  mao: ['māo', 'máo', 'mǎo', 'mào'],
  sheng: ['shēng', 'shéng', 'shěng', 'shèng'],
  yao: ['yāo', 'yáo', 'yǎo', 'yào'],
  shen: ['shēn', 'shén', 'shěn', 'shèn'],
  pian: ['piān', 'pián', 'piǎn', 'piàn'],
  pu: ['pū', 'pú', 'pǔ', 'pù'],
  hua: ['huā', 'huá', 'huà'],
  chou: ['chōu', 'chóu', 'chǒu', 'chòu'],
  qiu: ['qiū', 'qiú', 'qiǔ'],
  reng: ['rēng', 'réng'],
  zhao: ['zhāo', 'zháo', 'zhǎo', 'zhào'],
  zhua: ['zhuā', 'zhuǎ'],
  jie: ['jiē', 'jié', 'jiě', 'jiè', 'jie'],
  cong: ['cōng', 'cóng'],
  lun: ['lūn', 'lún', 'lǔn', 'lùn'],
  xiong: ['xiōng', 'xióng', 'xiòng'],
  fen: ['fēn', 'fén', 'fěn', 'fèn'],
  fa: ['fā', 'fá', 'fǎ', 'fà'],
  cang: ['cāng', 'cáng'],
  dan: ['dān', 'dǎn', 'dàn'],
  gou: ['gōu', 'gǒu', 'gòu'],
  liu: ['liū', 'liú', 'liǔ', 'liù'],
  wen: ['wēn', 'wén', 'wěn', 'wèn'],
  kang: ['kāng', 'káng', 'kàng'],
  fang: ['fāng', 'fáng', 'fǎng', 'fàng'],
  huo: ['huō', 'huó', 'huǒ', 'huò', 'huo'],
  dou: ['dōu', 'dǒu', 'dòu'],
  rong: ['róng', 'rǒng'],
  xin: ['xīn', 'xǐn', 'xìn'],
  chi: ['chī', 'chí', 'chǐ', 'chì'],
  yin: ['yīn', 'yín', 'yǐn', 'yìn'],
  kong: ['kōng', 'kǒng', 'kòng'],
  dui: ['duī', 'duì'],
  ban: ['bān', 'bǎn', 'bàn'],
  deng: ['dēng', 'děng', 'dèng'],
  shuang: ['shuāng', 'shuǎng'],
  shu: ['shū', 'shú', 'shǔ', 'shù'],
  huan: ['huān', 'huán', 'huǎn', 'huàn'],
  kan: ['kān', 'kǎn', 'kàn'],
  qiao: ['qiāo', 'qiáo', 'qiǎo', 'qiào'],
  zheng: ['zhēng', 'zhěng', 'zhèng'],
  hui: ['huī', 'huí', 'huǐ', 'huì'],
  pa: ['pā', 'pá', 'pà'],
  ai: ['āi', 'ái', 'ǎi', 'ài'],
  gu: ['gū', 'gǔ', 'gù'],
  ben: ['bēn', 'běn', 'bèn'],
  zhu: ['zhū', 'zhú', 'zhǔ', 'zhù'],
  ke: ['kē', 'ké', 'kě', 'kè'],
  bing: ['bīng', 'bǐng', 'bìng'],
  zuo: ['zuō', 'zuó', 'zuǒ', 'zuò'],
  hang: ['hāng', 'háng', 'hàng'],
  long: ['lóng', 'lǒng', 'lòng'],
  ping: ['pīng', 'píng'],
  mie: ['miē', 'miè'],
  dong: ['dōng', 'dǒng', 'dòng'],
  ka: ['kā', 'kǎ'],
  qia: ['qiā', 'qiá', 'qiǎ', 'qià'],
  zhan: ['zhān', 'zhǎn', 'zhàn'],
  lu: ['lū', 'lú', 'lǔ', 'lù', 'lu'],
  shuai: ['shuāi', 'shuǎi', 'shuài'],
  gui: ['guī', 'guǐ', 'guì'],
  xie: ['xiē', 'xié', 'xiě', 'xiè'],
  jia: ['jiā', 'jiá', 'jiǎ', 'jià', 'jia'],
  dian: ['diān', 'diǎn', 'diàn'],
  hao: ['hāo', 'háo', 'hǎo', 'hào'],
  yang: ['yāng', 'yáng', 'yǎng', 'yàng'],
  jiao: ['jiāo', 'jiáo', 'jiǎo', 'jiào'],
  tao: ['tāo', 'táo', 'tǎo', 'tào'],
  ling: ['líng', 'lǐng', 'lìng'],
  tan: ['tān', 'tán', 'tǎn', 'tàn'],
  ran: ['rán', 'rǎn'],
  min: ['mín', 'mǐn'],
  ao: ['āo', 'áo', 'ǎo', 'ào'],
  he: ['hē', 'hé', 'hè'],
  bai: ['bāi', 'bái', 'bǎi', 'bài'],
  zai: ['zāi', 'zǎi', 'zài'],
  ta: ['tā', 'tǎ', 'tà'],
  gua: ['guā', 'guǎ', 'guà'],
  yong: ['yōng', 'yóng', 'yǒng', 'yòng'],
  ce: ['cè'],
  wai: ['wāi', 'wǎi', 'wài'],
  chu: ['chū', 'chú', 'chǔ', 'chù'],
  niao: ['niǎo', 'niào'],
  bao: ['bāo', 'báo', 'bǎo', 'bào'],
  xuan: ['xuān', 'xuán', 'xuǎn', 'xuàn'],
  lan: ['lán', 'lǎn', 'làn'],
  tou: ['tōu', 'tóu', 'tòu'],
  han: ['hān', 'hán', 'hǎn', 'hàn'],
  ning: ['níng', 'nǐng', 'nìng'],
  xue: ['xuē', 'xué', 'xuě', 'xuè'],
  rang: ['rāng', 'ráng', 'rǎng', 'ràng'],
  xun: ['xūn', 'xún', 'xùn'],
  ni: ['nī', 'ní', 'nǐ', 'nì'],
  hong: ['hōng', 'hóng', 'hǒng', 'hòng'],
  nu: ['nú', 'nǔ', 'nù'],
  bian: ['biān', 'biǎn', 'biàn'],
  bang: ['bāng', 'bǎng', 'bàng'],
  xing: ['xīng', 'xíng', 'xǐng', 'xìng'],
  kao: ['kāo', 'kǎo', 'kào'],
  tuo: ['tuō', 'tuó', 'tuǒ', 'tuò'],
  lao: ['lāo', 'láo', 'lǎo', 'lào'],
  kuo: ['kuò'],
  sao: ['sāo', 'sǎo', 'sào'],
  de: ['dē', 'dé', 'de'],
  di: ['dī', 'dí', 'dǐ', 'dì'],
  mang: ['māng', 'máng', 'mǎng'],
  xiu: ['xiū', 'xiǔ', 'xiù'],
  piao: ['piāo', 'piáo', 'piǎo', 'piào'],
  po: ['pō', 'pó', 'pǒ', 'pò', 'po'],
  guo: ['guō', 'guó', 'guǒ', 'guò'],
  chen: ['chēn', 'chén', 'chěn', 'chèn'],
  yan: ['yān', 'yán', 'yǎn', 'yàn'],
  xu: ['xū', 'xú', 'xǔ', 'xù', 'xu'],
  jiang: ['jiāng', 'jiǎng', 'jiàng'],
  kua: ['kuā', 'kuǎ', 'kuà'],
  duo: ['duō', 'duó', 'duǒ', 'duò'],
  lie: ['liē', 'liě', 'liè'],
  cheng: ['chēng', 'chéng', 'chěng', 'chèng'],
  ga: ['gā', 'gá', 'gǎ', 'gà'],
  mai: ['mái', 'mǎi', 'mài'],
  ci: ['cī', 'cí', 'cǐ', 'cì'],
  zhen: ['zhēn', 'zhěn', 'zhèn'],
  dang: ['dāng', 'dǎng', 'dàng'],
  zao: ['zāo', 'záo', 'zǎo', 'zào'],
  chong: ['chōng', 'chóng', 'chǒng', 'chòng'],
  tuan: ['tuān', 'tuán', 'tuǎn', 'tuàn'],
  lv: ['lǘ', 'lǚ', 'lǜ'],
  tong: ['tōng', 'tóng', 'tǒng', 'tòng'],
  sui: ['suī', 'suí', 'suǐ', 'suì'],
  ze: ['zé', 'zè'],
  rou: ['róu', 'ròu'],
  nian: ['niān', 'nián', 'niǎn', 'niàn'],
  diu: ['diū'],
  she: ['shē', 'shé', 'shě', 'shè'],
  pang: ['pāng', 'páng', 'pǎng', 'pàng'],
  hou: ['hōu', 'hóu', 'hǒu', 'hòu'],
  heng: ['hēng', 'héng', 'hèng'],
  zhou: ['zhōu', 'zhóu', 'zhǒu', 'zhòu'],
  kuai: ['kuǎi', 'kuài'],
  sha: ['shā', 'shá', 'shǎ', 'shà'],
  chuang: ['chuāng', 'chuáng', 'chuǎng', 'chuàng'],
  lei: ['lēi', 'léi', 'lěi', 'lèi', 'lei'],
  ming: ['míng', 'mǐng', 'mìng'],
  se: ['sè'],
  shai: ['shāi', 'shǎi', 'shài'],
  zhuang: ['zhuāng', 'zhuǎng', 'zhuàng'],
  qing: ['qīng', 'qíng', 'qǐng', 'qìng'],
  chan: ['chān', 'chán', 'chǎn', 'chàn'],
  jue: ['juē', 'jué', 'juě', 'juè'],
  hai: ['hāi', 'hái', 'hǎi', 'hài'],
  guan: ['guān', 'guǎn', 'guàn'],
  mi: ['mī', 'mí', 'mǐ', 'mì'],
  tang: ['tāng', 'táng', 'tǎng', 'tàng'],
  zhai: ['zhāi', 'zhái', 'zhǎi', 'zhài'],
  an: ['ān', 'ǎn', 'àn'],
  jun: ['jūn', 'jùn'],
  e: ['ē', 'é', 'ě', 'è', 'e'],
  song: ['sōng', 'sǒng', 'sòng'],
  nong: ['nóng', 'nòng'],
  na: ['nā', 'ná', 'nǎ', 'nà', 'na'],
  sun: ['sūn', 'sǔn'],
  huai: ['huái', 'huài'],
  rao: ['ráo', 'rǎo', 'rào'],
  zou: ['zōu', 'zǒu', 'zòu'],
  chao: ['chāo', 'cháo', 'chǎo', 'chào'],
  zhe: ['zhē', 'zhé', 'zhě', 'zhè', 'zhe'],
  qiang: ['qiāng', 'qiáng', 'qiǎng', 'qiàng'],
  pao: ['pāo', 'páo', 'pǎo', 'pào'],
  keng: ['kēng'],
  que: ['quē', 'qué', 'què'],
  qin: ['qīn', 'qín', 'qǐn', 'qìn'],
  su: ['sū', 'sú', 'sù'],
  du: ['dū', 'dú', 'dǔ', 'dù'],
  geng: ['gēng', 'gěng', 'gèng'],
  liang: ['liáng', 'liǎng', 'liàng'],
  fou: ['fǒu'],
  lai: ['lái', 'lài'],
  lian: ['lián', 'liǎn', 'liàn'],
  kuang: ['kuāng', 'kuáng', 'kuǎng', 'kuàng'],
  dun: ['dūn', 'dǔn', 'dùn'],
  zu: ['zū', 'zú', 'zǔ'],
  nan: ['nān', 'nán', 'nǎn', 'nàn'],
  kun: ['kūn', 'kǔn', 'kùn'],
  chui: ['chuī', 'chuí'],
  bie: ['biē', 'bié', 'biě', 'biè'],
  shun: ['shǔn', 'shùn'],
  gao: ['gāo', 'gǎo', 'gào'],
  wo: ['wō', 'wǒ', 'wò'],
  luan: ['luán', 'luǎn', 'luàn'],
  mei: ['méi', 'měi', 'mèi'],
  ti: ['tī', 'tí', 'tǐ', 'tì'],
  fo: ['fó'],
  lin: ['līn', 'lín', 'lǐn', 'lìn'],
  mian: ['mián', 'miǎn', 'miàn'],
  tiao: ['tiāo', 'tiáo', 'tiǎo', 'tiào'],
  ying: ['yīng', 'yíng', 'yǐng', 'yìng'],
  ku: ['kū', 'kǔ', 'kù'],
  leng: ['lēng', 'léng', 'lěng', 'lèng'],
  run: ['rùn'],
  pan: ['pān', 'pán', 'pàn'],
  can: ['cān', 'cán', 'cǎn', 'càn'],
  zhuo: ['zhuō', 'zhuó'],
  pei: ['pēi', 'péi', 'pèi'],
  qiong: ['qióng'],
  ceng: ['cēng', 'céng', 'cèng'],
  a: ['ā', 'á', 'ǎ', 'à', 'a'],
  zhui: ['zhuī', 'zhuì'],
  miao: ['miāo', 'miáo', 'miǎo', 'miào'],
  chun: ['chūn', 'chún', 'chǔn'],
  zong: ['zōng', 'zǒng', 'zòng'],
  biao: ['biāo', 'biǎo', 'biào'],
  guai: ['guāi', 'guǎi', 'guài'],
  pai: ['pāi', 'pái', 'pǎi', 'pài'],
  chai: ['chāi', 'chái', 'chǎi', 'chài'],
  la: ['lā', 'lá', 'lǎ', 'là', 'la'],
  ruo: ['ruò'],
  sang: ['sāng', 'sǎng', 'sàng'],
  ruan: ['ruán', 'ruǎn'],
  ken: ['kěn', 'kèn'],
  ang: ['āng', 'áng', 'àng'],
  ne: ['né', 'nè', 'ne'],
  tie: ['tiē', 'tiě', 'tiè'],
  luo: ['luō', 'luó', 'luǒ', 'luò', 'luo'],
  die: ['diē', 'dié'],
  suo: ['suō', 'suǒ'],
  pin: ['pīn', 'pín', 'pǐn', 'pìn'],
  peng: ['pēng', 'péng', 'pěng', 'pèng'],
  hun: ['hūn', 'hún', 'hùn'],
  nve: ['nüè'],
  cu: ['cū', 'cú', 'cù'],
  nao: ['nāo', 'náo', 'nǎo', 'nào'],
  juan: ['juān', 'juǎn', 'juàn'],
  lang: ['lāng', 'láng', 'lǎng', 'làng'],
  shua: ['shuā', 'shuǎ', 'shuà'],
  meng: ['mēng', 'méng', 'měng', 'mèng'],
  lou: ['lōu', 'lóu', 'lǒu', 'lòu', 'lou'],
  cen: ['cēn', 'cén'],
  zhuai: ['zhuài'],
  shuan: ['shuān', 'shuàn'],
  nuo: ['nuó', 'nuò'],
  mou: ['mōu', 'móu', 'mǒu'],
  cao: ['cāo', 'cáo', 'cǎo'],
  huang: ['huāng', 'huáng', 'huǎng', 'huàng'],
  beng: ['bēng', 'béng', 'běng', 'bèng'],
  zan: ['zān', 'zán', 'zǎn', 'zàn'],
  ha: ['hā', 'há', 'hǎ', 'hà'],
  yo: ['yō', 'yo'],
  zen: ['zěn', 'zèn'],
  duan: ['duān', 'duǎn', 'duàn'],
  lia: ['liǎ'],
  hen: ['hén', 'hěn', 'hèn'],
  pen: ['pēn', 'pén', 'pèn'],
  shuo: ['shuō', 'shuò'],
  sa: ['sā', 'sǎ', 'sà'],
  tui: ['tuī', 'tuí', 'tuǐ', 'tuì'],
  gei: ['gěi'],
  nie: ['niē', 'niè'],
  man: ['mān', 'mán', 'mǎn', 'màn'],
  cuo: ['cuō', 'cuó', 'cuǒ', 'cuò'],
  re: ['rě', 'rè'],
  gen: ['gēn', 'gén', 'gěn', 'gèn'],
  o: ['ō', 'ó', 'ò'],
  en: ['ēn', 'èn'],
  hng: ['hng'],
  zei: ['zéi'],
  zang: ['zāng', 'zǎng', 'zàng'],
  zuan: ['zuān', 'zuǎn', 'zuàn'],
  te: ['tè'],
  weng: ['wēng', 'wěng', 'wèng'],
  cui: ['cuī', 'cuǐ', 'cuì'],
  zhun: ['zhūn', 'zhǔn'],
  teng: ['tēng', 'téng'],
  pou: ['pōu', 'póu', 'pǒu'],
  kuan: ['kuān', 'kuǎn'],
  bin: ['bīn', 'bìn'],
  shei: ['shéi'],
  niang: ['niáng', 'niàng'],
  neng: ['néng'],
  lve: ['lüè'],
  nin: ['nín'],
  dei: ['dēi', 'děi'],
  cou: ['còu'],
  chuo: ['chuō', 'chuò'],
  zeng: ['zēng', 'zèng'],
  chuai: ['chuāi', 'chuǎi', 'chuài'],
  sou: ['sōu', 'sǒu', 'sòu'],
  sen: ['sēn'],
  gun: ['gǔn', 'gùn'],
  zui: ['zuǐ', 'zuì'],
  hei: ['hēi'],
  rui: ['ruí', 'ruǐ', 'ruì'],
  zun: ['zūn', 'zǔn'],
  cuan: ['cuān', 'cuán', 'cuàn'],
  jiong: ['jiōng', 'jiǒng'],
  qun: ['qūn', 'qún'],
  suan: ['suān', 'suàn'],
  nuan: ['nuǎn'],
  sai: ['sāi', 'sài'],
  miu: ['miù'],
  pie: ['piē', 'piě'],
  seng: ['sēng'],
  nen: ['nèn'],
  ca: ['cā'],
  nang: ['nāng', 'náng', 'nǎng', 'nàng'],
  m: ['ḿ', 'm̀'],
  kei: ['kēi'],
  lo: ['lo'],
  ei: ['ēi', 'éi', 'ěi', 'èi'],
  ng: ['ńg', 'ňg', 'ǹg'],
  dia: ['diǎ'],
  nou: ['nòu'],
  den: ['dèn'],
};
